In [1]:
import numpy as np


In [2]:
y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [20]:
y_true

array([0.3, 0.7, 1. , 0. , 0.5])

MEAN ABSOLUTE ERROR
---

In [3]:
def mae(y_true,y_predicted):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("Tota error:",total_error)

    mae=total_error/len(y_predicted)
    print("MAE:",mae)
    return mae

MEAN SQUARED ERROR
---

In [4]:
def mse(y_true,y_predicted):
    total_mse_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_mse_error+=(yt-yp)**2
    print("Total mse error:",total_mse_error)

    mse=total_mse_error/len(y_true)
    print("MSE:",mse)
    return mse

In [5]:
mae(y_true,y_predicted)

Tota error: 2.5
MAE: 0.5


0.5

In [6]:
mse(y_true,y_predicted)

Total mse error: 1.83
MSE: 0.366


0.366

MEAN ABSOLUTE ERROR USING NUMPY
---

In [7]:
# total error
np.sum(np.abs(y_true-y_predicted))

2.5

In [8]:
# mean absolute error
np.mean(np.abs(y_true-y_predicted))

0.5

MEAN SQUARED ERROR USING NUMPY
---

In [9]:
np.sum(np.square(y_true-y_predicted))

1.83

In [10]:
np.mean(np.square(y_true-y_predicted))

0.366

In [11]:
np.log(y_predicted)
# This is an issue..output shows:  array([  0.,   0., -inf, -inf,   0.])

C:\Users\kevin\AppData\Local\Temp\ipykernel_29372\457206481.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

LOG LOSS OR BINARY CROSS ENTROPY
---

In [12]:
epsilon=1e-15

The value of 1e-15 is 0.000000000000001

In [13]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [16]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [17]:
def log_loss(y_true,y_predicted_new):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


In [18]:
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [19]:
log_loss(y_true,y_predicted_new)

17.2696280766844