In [81]:
import numpy as np

In [82]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expense=np.array([[80,90,100],[10,16,20],[8,10,10]])

# the above is multi dimensional arrays

In [83]:
profit=revenue-expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [84]:
price_per_product=np.array([1000,400,1200])
product_saled_yearly=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [85]:
total_sales=price_per_product*product_saled_yearly
total_sales

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [86]:
np.dot(price_per_product,product_saled_yearly)

array([34400, 50000, 64400])

Exercise 1

In [87]:
company_revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
one_usd=np.array([75])
sales=one_usd*company_revenue
sales

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Exercise 2

In [88]:
price_per_flower=np.array([20,30,15])
flower_monthly_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
np.dot(price_per_flower,flower_monthly_sold)

array([1900, 2640, 1430])