In [224]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [225]:
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [226]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [227]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [228]:
df.shape

(768, 9)

In [229]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [230]:
df['Outcome'].value_counts()  
# Imbalance dataset

Outcome
0    500
1    268
Name: count, dtype: int64

In [231]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [232]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [233]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [234]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [235]:
from keras.models import Sequential
from keras.layers import Dense
ann=Sequential()

ann.add(Dense(units=8,activation='relu'))
ann.add(Dense(units=10,activation='relu'))
ann.add(Dense(units=6,activation='relu'))
ann.add(Dense(1,activation='sigmoid'))


In [236]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [237]:
ann.fit(x_train,y_train,epochs=100,batch_size=12)

Epoch 1/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4842 - loss: 0.7070
Epoch 2/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6499 - loss: 0.6542
Epoch 3/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6592 - loss: 0.6276 
Epoch 4/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6667 - loss: 0.6000 
Epoch 5/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6704 - loss: 0.5687 
Epoch 6/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6872 - loss: 0.5356 
Epoch 7/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7449 - loss: 0.5111 
Epoch 8/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7691 - loss: 0.4916 
Epoch 9/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7728 - loss: 0.4803 
Epoch 10/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7858 - loss: 0.4738 
Epoch 11/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7858 - loss: 0.4684 
Epoch 12/100
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - 

In [238]:
ann.evaluate(x_test,y_test)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8009 - loss: 0.4640 


[0.4639531373977661, 0.8008658289909363]

In [239]:
y_pred=ann.predict(scaler.transform([[6,148,72,35,0,33.6,0.627,50]]))
if y_pred>=0.5:
    print("Diabetic Patient")
else:
    print("Not Diabetic Patient")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Diabetic Patient


In [240]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

Method 1: UnderSampling
---

In [241]:
from sklearn.metrics import classification_report

def ANN(x_train,y_train,x_test,y_test,loss,weights):
    model=keras.Sequential([
        keras.layers.Dense(8,activation='relu'),
        keras.layers.Dense(10,activation='relu'),
        keras.layers.Dense(6,activation='relu'),
        keras.layers.Dense(1,activation='sigmoid')
    ])

    model.compile(optimizer='adam',loss=loss,metrics=['accuracy'])

    if weights==-1:
        model.fit(x_train,y_train,epochs=200)
    else:
        model.fit(x_train,y_train,epochs=100,class_weight=weights)
    
    print(model.evaluate(x_test,y_test))

    y_pred=model.predict(x_test)
    y_pred=np.round(y_pred)

    print("Classifaction report: \n",classification_report(y_test,y_pred))
    return y_pred



In [242]:
y_pred1=ANN(x_train,y_train,x_test,y_test,'binary_crossentropy',-1)
y_pred1.reshape(-1)

Epoch 1/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6369 - loss: 0.6860   
Epoch 2/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6667 - loss: 0.6721 
Epoch 3/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6853 - loss: 0.6550 
Epoch 4/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7020 - loss: 0.6339 
Epoch 5/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7114 - loss: 0.6138 
Epoch 6/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7188 - loss: 0.5924 
Epoch 7/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7188 - loss: 0.5741 
Epoch 8/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7225 - loss: 0.5597 
Epoch 9/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7169 - loss: 0.5473 
Epoch 10/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7151 - loss: 0.5374 
Epoch 11/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7169 - loss: 0.5270 
Epoch 12/200
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/ste

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1.,
       0., 0., 1., 0., 0.

In [243]:
class_0,class_1=df['Outcome'].value_counts()
df_class_0=df.loc[df['Outcome']==0]
df_class_1=df.loc[df['Outcome']==1]
df_class_0

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6   
3              1       89             66             23       94  28.1   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
1                       0.351   31        0  
3                       0.167   21        0  
5                       0.201   30        0  
7                       0.134   29        0  
10                      0.191   30        0  
..                        ...  ...      ...  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
767                     0.315   23        0  

[500 rows x 9 columns]

In [244]:
df_class_0.shape

(500, 9)

In [245]:
df_class_1.shape

(268, 9)

The below is an imbalanced dataset.

because, class_0 contains has 500 values but class_1 has only 268 values

In [246]:
class_0

500

In [247]:
class_1

268

In [248]:
df_class_0.sample(class_1).shape

(268, 9)

In [249]:
df_class_0_under=df_class_0.sample(class_1)
df_class_0_under
df_test_under=pd.concat([df_class_0_under,df_class_1],axis=0)
df_test_under
print(df_test_under['Outcome'].value_counts())

Outcome
0    268
1    268
Name: count, dtype: int64


In [250]:
x1=df_test_under.drop(['Outcome'],axis=1)
y1=df_test_under['Outcome']

In [251]:
x1.shape

(536, 8)

In [252]:
y1.shape

(536,)

In [253]:
print(len(x1), len(y1))


536 536


In [254]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.2,random_state=42,stratify=y1)

In [255]:
y_train1.value_counts()

Outcome
1    214
0    214
Name: count, dtype: int64

In [256]:
y_test1.value_counts()

Outcome
0    54
1    54
Name: count, dtype: int64

In [257]:
y_predicted=ANN(x_train1,y_train1,x_test1,y_test1,'binary_crossentropy',-1)

Epoch 1/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5000 - loss: 26.6125   
Epoch 2/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5000 - loss: 17.6075 
Epoch 3/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4953 - loss: 11.7969 
Epoch 4/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5047 - loss: 7.9852  
Epoch 5/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4930 - loss: 5.3616 
Epoch 6/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4907 - loss: 3.5397 
Epoch 7/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4696 - loss: 2.4485 
Epoch 8/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4369 - loss: 1.7316 
Epoch 9/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4556 - loss: 1.2769 
Epoch 10/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4696 - loss: 1.0042 
Epoch 11/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4883 - loss: 0.8313 
Epoch 12/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms

In [258]:
y_predicted=y_predicted.reshape(-1)
y_predicted

array([0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 1., 0., 0., 1., 1.], dtype=float32)

Precision and recall score both classes have increased after balancing imbalanced dataset

Method 2: OverSampling
---

In [259]:
class_0,class_1

(500, 268)

In [260]:
df_class_1_over=df_class_1.sample(class_0,replace=True) #oversampling df_class_1 by duplicating
df_class_1_over
df_test_over=pd.concat([df_class_1_over,df_class_0],axis=0)
df_test_over

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
748            3      187             70             22      200  36.4   
730            3      130             78             23       79  28.4   
131            9      122             56              0        0  33.3   
715            7      187             50             33      392  33.9   
590           11      111             84             40        0  46.8   
..           ...      ...            ...            ...      ...   ...   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
748                     0.408   36        1  
730                     0.323   34        1  
131                     1.114   33        1  
715                     0.826   34        1  
590                     0.925   45        1  
..                        ...  ...      ...  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
767                     0.315   23        0  

[1000 rows x 9 columns]

In [261]:
df_test_over['Outcome'].value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [262]:
x2=df_test_over.iloc[:,:-1]
y2=df_test_over.iloc[:,-1]

In [263]:
from sklearn.model_selection import train_test_split
x_train2,x_test2,y_train2,y_test2=train_test_split(x2,y2,test_size=0.2,random_state=42,stratify=y2)

In [264]:
y_train2.value_counts()

Outcome
1    400
0    400
Name: count, dtype: int64

In [265]:
y_test2.value_counts()

Outcome
1    100
0    100
Name: count, dtype: int64

In [266]:
y_predicted2=ANN(x_train2,y_train2,x_test2,y_test2,'binary_crossentropy',-1)
y_predicted2.reshape(-1)

Epoch 1/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5175 - loss: 2.2459   
Epoch 2/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5288 - loss: 1.6433 
Epoch 3/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5300 - loss: 1.2888 
Epoch 4/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5150 - loss: 0.9469 
Epoch 5/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5300 - loss: 0.8211 
Epoch 6/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5462 - loss: 0.7714 
Epoch 7/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5400 - loss: 0.7443 
Epoch 8/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5425 - loss: 0.7246 
Epoch 9/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5700 - loss: 0.7014 
Epoch 10/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5763 - loss: 0.6908 
Epoch 11/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5813 - loss: 0.6862 
Epoch 12/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/ste

array([1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [267]:
import numpy as np
unique, counts = np.unique(y, return_counts=True)
print(dict(zip(unique, counts)))


{0: 500, 1: 268}


Method 3: SMOTE
---

In [268]:
x_smote=df.iloc[:,:-1]
y_smote=df.iloc[:,-1]

In [269]:
y_smote.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [270]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(sampling_strategy='minority')
x_resampled,y_resampled=sm.fit_resample(x_smote,y_smote)
y_resampled.value_counts()

Outcome
1    500
0    500
Name: count, dtype: int64

In [271]:
from sklearn.model_selection import train_test_split
x_train_sm,x_test_sm,y_train_sm,y_test_sm=train_test_split(x_resampled,y_resampled,test_size=0.2,random_state=42,stratify=y_resampled)

In [272]:
y_train_sm.value_counts()

Outcome
1    400
0    400
Name: count, dtype: int64

In [273]:
y_test_sm.value_counts()

Outcome
1    100
0    100
Name: count, dtype: int64

In [274]:
y_pred_smote=ANN(x_train_sm,y_train_sm,x_test_sm,y_test_sm,'binary_crossentropy',-1)
y_pred_smote.reshape(-1)

Epoch 1/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5562 - loss: 2.8544   
Epoch 2/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6050 - loss: 1.2372 
Epoch 3/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5775 - loss: 0.8607 
Epoch 4/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5650 - loss: 0.7486 
Epoch 5/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5763 - loss: 0.7062 
Epoch 6/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5938 - loss: 0.6784 
Epoch 7/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6037 - loss: 0.6758 
Epoch 8/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5600 - loss: 0.6873 
Epoch 9/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5913 - loss: 0.6677 
Epoch 10/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6037 - loss: 0.6621 
Epoch 11/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5950 - loss: 0.6659 
Epoch 12/200
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/ste

array([1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0.], dtype=float32)

Method 4: Use of Ensemble with undersampling
---

In [275]:
x_ensemble=df.iloc[:,:-1]
y_ensemble=df.iloc[:,-1]

In [276]:
y_ensemble.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [277]:
from sklearn.model_selection import train_test_split
x_train_ensm,x_test_ensm,y_train_ensm,y_test_ensm=train_test_split(x_ensemble,y_ensemble,test_size=0.2,random_state=42,stratify=y_ensemble)

In [278]:
y_test_ensm.value_counts()

Outcome
0    100
1     54
Name: count, dtype: int64

In [279]:
df_class_0_ensemble=df.loc[df['Outcome']==0]
df_class_1_ensemble=df.loc[df['Outcome']==1]
df_class_0_ensemble['Outcome'].value_counts()
df_class_1_ensemble['Outcome'].value_counts()
# 500/268
# so,df_class_0_ensemble is splitted into 1.8656716417910448 batches

Outcome
1    268
Name: count, dtype: int64

In [280]:
df_class_0_ensemble.shape,df_class_1_ensemble.shape

((500, 9), (268, 9))

In [281]:
df_class_0_ensemble[:268].shape #here we are taking only 268 elements from class_0(slicing techinque is used here)
# so now ,class_0 and class_1 have equal number of 0 and 1

(268, 9)

In [282]:
df_ensemble=pd.concat([df_class_0_ensemble[:268],df_class_1_ensemble],axis=0)
df_ensemble

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6   
3              1       89             66             23       94  28.1   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
755            1      128             88             39      110  36.5   
757            0      123             72              0        0  36.3   
759            6      190             92              0        0  35.5   
761            9      170             74             31        0  44.0   
766            1      126             60              0        0  30.1   

     DiabetesPedigreeFunction  Age  Outcome  
1                       0.351   31        0  
3                       0.167   21        0  
5                       0.201   30        0  
7                       0.134   29        0  
10                      0.191   30        0  
..                        ...  ...      ...  
755                     1.057   37        1  
757                     0.258   52        1  
759                     0.278   66        1  
761                     0.403   43        1  
766                     0.349   47        1  

[536 rows x 9 columns]

In [283]:
df_ensemble['Outcome'].value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [284]:
def get_batch(df_majority,df_minority,start,end):
    df_train=pd.concat([df_majority[start:end],df_minority],axis=0)
    x=df_train.iloc[:,:-1]
    y=df_train.iloc[:,-1]

    from sklearn.model_selection import train_test_split
    x_train_ensm,x_test_ensm,y_train_ensm,y_test_ensm=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
    
    return x_train_ensm,y_train_ensm,x_test_ensm,y_test_ensm

In [285]:
x_train_ensm1,y_train_ensm1,x_test_ensm1,y_test_ensm1=get_batch(df_class_0_ensemble,df_class_1_ensemble,0,268)
y_train_ensm1.value_counts()

Outcome
1    214
0    214
Name: count, dtype: int64

In [286]:
y_test_ensm1.value_counts()

Outcome
0    54
1    54
Name: count, dtype: int64

In [287]:
y_pred_ensm1=ANN(x_train_ensm1,y_train_ensm1,x_test_ensm1,y_test_ensm1,'binary_crossentropy',-1)
y_pred_ensm1.reshape(-1)

Epoch 1/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5794 - loss: 2.6737   
Epoch 2/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5748 - loss: 1.9812 
Epoch 3/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5771 - loss: 1.5120 
Epoch 4/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5467 - loss: 1.0821 
Epoch 5/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5444 - loss: 0.9098 
Epoch 6/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5397 - loss: 0.9052 
Epoch 7/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5537 - loss: 0.8659 
Epoch 8/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5537 - loss: 0.8687 
Epoch 9/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5257 - loss: 0.9089 
Epoch 10/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5748 - loss: 0.8142 
Epoch 11/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5467 - loss: 0.7992 
Epoch 12/200
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/ste

array([0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 1., 0.], dtype=float32)

In [288]:
x_train_ensm1.shape[0]+x_test_ensm1.shape[0]

536

In [289]:
x_train_ensm2,y_train_ensm2,x_test_ensm2,y_test_ensm2=get_batch(df_class_0_ensemble,df_class_1_ensemble,268,536)
y_pred_ensm2=ANN(x_train_ensm2,y_train_ensm2,x_test_ensm2,y_test_ensm2,'binary_crossentropy',-1)
y_pred_ensm2.reshape(-1)

Epoch 1/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4825 - loss: 5.9224   
Epoch 2/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4875 - loss: 3.5452 
Epoch 3/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5050 - loss: 1.9781 
Epoch 4/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5125 - loss: 1.0816 
Epoch 5/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5325 - loss: 0.7240 
Epoch 6/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5325 - loss: 0.6885 
Epoch 7/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5575 - loss: 0.6863 
Epoch 8/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5575 - loss: 0.6861 
Epoch 9/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5575 - loss: 0.6857 
Epoch 10/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5600 - loss: 0.6851 
Epoch 11/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5575 - loss: 0.6845 
Epoch 12/200
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/ste

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
      dtype=float32)

In [290]:
y_test_ensm2.shape


(100,)

In [291]:
y_test_ensm1.shape


(108,)

In [292]:
x_train_ensm2.shape

(400, 8)

In [293]:
y_pred_ensm1.shape

(108, 1)

In [294]:
y_pred_ensm2.shape

(100, 1)

In [306]:
y_pred_final=y_pred_ensm1.copy()

for i in range(len(y_pred_ensm2)):
    n_ones=y_pred_ensm1[i]+y_pred_ensm2[i]
    if n_ones>1:
        y_pred_final[i]=1
    else:
        y_pred_final[i]=0

In [307]:
print(classification_report(y_test_ensm1,y_pred_final))

              precision    recall  f1-score   support

           0       0.62      0.74      0.67        54
           1       0.67      0.54      0.60        54

    accuracy                           0.64       108
   macro avg       0.64      0.64      0.64       108
weighted avg       0.64      0.64      0.64       108

